language: node_js
node_js:
  - node
  - lts/*
script:
  - npm run lint
  # We don't need to run standalone test on Travis,
  # due to fact that nyc is display normal output from mocha
  # - npm run test
  - npm run test-coverage
  - npm run test-coverage-report
